

# This file was *autogenerated* from the file simple.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)# sage simple.sage

print(Matrix(IntegerModRing(_sage_const_7 ), [[_sage_const_1 , _sage_const_2 ], [_sage_const_3 ,_sage_const_4 ]]).inverse())
print(Matrix([[_sage_const_1 , _sage_const_2 ], [_sage_const_3 ,_sage_const_4 ]]).inverse())


